### ISSUE TITLE
Multi-page corpus selection not working

### ISSUE THREAD

**Issue by anjackson** [ukwa/shine#60]
A bug report from a user (internal ticket 1501-0960).

> I am trying to isolate my corpus for the final section of my bursary holder report and I'm having a problem. Having saved a selection of search strings I now need to manually exclude irrelevant material. I am excluding individual results and hosts. This is working fine when I am working on page 1 of my results. However, when I click on to page 2 of my results, Shine is removing all my filters (hence my search results shoot up from 110 to 2185). I'm not sure why this is happening but it is preventing me from weeding my results.

Note that this is rather urgent.

/cc @peterwebster

**Comment by peterwebster** [comment]
Possibly related to #59

**Comment by peterwebster** [comment]
It would be good to prioritise this @kinmanli

**Comment by kinmanli** [comment]
@peterwebster @anjackson 

Fixed issue by applying inverts to the responseparameter set in the backend. Also, fixing the frontend js issues with the facet links when filtering different options.

Fixed issue with showing "include facets" as excludes in "search summary". Added, modal loader when paginating

**Comment by peterwebster** [comment]
@kinmanli does /shine need redeploying ?

**Comment by peterwebster** [comment]
@kinmanli I'm still getting the issue.

See Exclude Hosts applied to page 1 of results here:
http://www.webarchive.org.uk/shine/search?page=1&invert=&facet.fields=public_suffix&invert=&invert=&invert=&invert=&action=search&query=%22rowan+williams%22+sharia&tab=results&sort=content_type_norm&order=asc&excludeHost=blog.newhumanist.org.uk&excludeHost=blog.newhumanist.org.uk&excludeHost=secularism.org.uk&excludeHost=blogs.telegraph.co.uk&excludeHost=politicalopinions.co.uk&mode=full

but if users clicks on to page 2, the exclusions get dropped (watch the total number of results tick up again).

http://www.webarchive.org.uk/shine/search?query=%22rowan+williams%22+sharia&page=2&sort=content_type_norm&facet.fields=public_suffix&order=asc&tab=results&action=search&mode=full

**Comment by kinmanli** [comment]
@peterwebster Where is the "exclude hosts" option?

**Comment by peterwebster** [comment]
It's in the Actions dropdown...

On Mon, Feb 9, 2015 at 2:22 PM, kinmanli <notifications@github.com> wrote:

> @peterwebster <https://github.com/peterwebster> Where is the "exclude
> hosts" option?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ukwa/shine/issues/60#issuecomment-73515816>.
>



-- 
*Dr Peter Webster*
*peterwebster6@gmail.com <peterwebster6@gmail.com>*
Twitter: *@pj_webster*
*http://peterwebster.me  <http://peterwebster.me>*
*http://websterresearchconsulting.com/ *
<http://websterresearchconsulting.com/>

**Comment by peterwebster** [comment]
Hi @kinmanli 

When trying to exclude hosts from a set of search results (   http://www.webarchive.org.uk/shine/search/advanced?page=1&facet.fields=public_suffix&addFacet=&action=search&proximityPhrase1=rowan+williams&proximityPhrase2=sharia&proximity=20&url=bbc.co.uk&sort=content_type_norm&order=asc&excludeHost=timesonline.co.uk&excludeHost=secularism.org.uk )

I get:


Execution exception[[RemoteSolrException: org.apache.solr.search.SyntaxError: Cannot parse ' AND -host:"timesonline.co.uk" AND -host:"secularism.org.uk" "rowan williams sharia"~20': Encountered " <AND> "AND "" at line 1, column 1. Was expecting one of: <NOT> ... "+" ... "-" ... <BAREOPER> ... "(" ... "*" ... <QUOTED> ... <TERM> ... <PREFIXTERM> ... <WILDTERM> ... <REGEXPTERM> ... "[" ... "{" ... <LPARAMS> ... <NUMBER> ... <TERM> ... "*" ... ]]

**Comment by peterwebster** [comment]
@GilHoggarth could you redeploy Shine, if it hasn't been since yesterday ?

**Comment by GilHoggarth** [comment]
Probably... (got it wrong last time.) Trying now.

**Comment by GilHoggarth** [comment]
Think that's done now, redeployed I mean.

**Comment by peterwebster** [comment]
Thanks @GilHoggarth 

@kinmanli after Gil's redeployment just now, I had a further go.

http://www.webarchive.org.uk/shine/search?query=%22rowan+williams%22&page=2&sort=content_type_normnull&facet.fields=public_suffix&excludeHost=conrad.blackwellpublishers.co.uk&excludeHost=info.cf.ac.uk&excludeHost=www.archinet.co.uk&sort=content_type_norm&order=asc&tab=results&action=search&mode=full

I implemented the exclusions on page 1, and then clicking on to page 2 now gives a different error:

Execution exception[[RemoteSolrException: sort param field can't be found: content_type_normnull]]

**Comment by kinmanli** [comment]
@peterwebster yes I'm looking at that one now as solr was down earlier and couldn't re-test it.

**Comment by kinmanli** [comment]
@peterwebster 

Fixed issues with exclude hosts. Just issue with ID for "excludes" to fix

**Comment by kinmanli** [comment]
fixed the issue with excluding results by encoding parameter

**Comment by peterwebster** [comment]
@kinmanli yes, do please redeploy

**Comment by kinmanli** [comment]
@peterwebster redeployed

**Comment by peterwebster** [comment]
@kinmanli this now works just fine when the user starts with the simple search.

If however, I run a proximity search from within the Advanced search, and then try to exclude hosts, I get a Solr exception.

That is:  this search works OK:

http://www.webarchive.org.uk/shine/search/advanced?proximityPhrase1=rowan+williams&proximityPhrase2=sharia&proximity=25&action=search&sort=content_type_norm&order=asc

but if I select and try to exclude the first host (www2.warwick.ac.uk), I get this:

Execution exception[[RemoteSolrException: org.apache.solr.search.SyntaxError: Cannot parse ' AND -host:"www2.warwick.ac.uk" "rowan williams sharia"~25': Encountered " <AND> "AND "" at line 1, column 1. Was expecting one of: <NOT> ... "+" ... "-" ... <BAREOPER> ... "(" ... "*" ... <QUOTED> ... <TERM> ... <PREFIXTERM> ... <WILDTERM> ... <REGEXPTERM> ... "[" ... "{" ... <LPARAMS> ... <NUMBER> ... <TERM> ... "*" ... ]]

(the URL that prompts this is:  http://www.webarchive.org.uk/shine/search/advanced?page=1&facet.fields=public_suffix&addFacet=&action=search&proximityPhrase1=rowan+williams&proximityPhrase2=sharia&proximity=25&sort=content_type_norm&order=asc&excludeHost=www2.warwick.ac.uk

**Comment by kinmanli** [comment]
@peterwebster fixed and redeployed

![2015-02-12 14-33-26_advanced search](https://cloud.githubusercontent.com/assets/1652105/6169243/012ab56c-b2c4-11e4-9870-8ca134323ebb.png)

**Comment by peterwebster** [comment]
OK, closing this ticket now, and about to open a new one to make one outstanding issue clearer.
